# https://www.netlify.com/docs/netlify-toml-reference/

[Settings]
  ID = ""

[Build]
  Publish = ""
  Functions = ""
  command = "npm run prod"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
